spring:
  datasource:
    url: jdbc:mysql://gz-cdb-rtzggr55.sql.tencentcdb.com:56814/javaee
    username: user
    password: 789456123@qqcom
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  h2:
    console:
      enabled: true

